# Site settings
   title: Vahid's Website
   description: Welcome to my personal website
   url: "https://vnourozi.github.io" # Update this line
   
   # Build settings
   theme: minima
   
   # GitHub information
   github_username: vnourozi # Update this line
   
   # Other settings
   markdown: kramdown
   permalink: /blog/:year/:month/:day/:title/
